name: pr-checker

on:
  pull_request_target:
    types: [opened]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Pull request
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ðŸ¤­ æ„Ÿè°¢ä½ çš„æäº¤ï¼Œè¯·æ£€æŸ¥ä½ çš„æ”¹åŠ¨æ˜¯å¦ç¬¦åˆä»¥ä¸‹é¡¹ç›®è§„èŒƒã€‚
            
            > ðŸ¤­ Thank you for your contribution. Please check if your changes comply with the following project specifications. 

            ### 1. æ ¼å¼åŒ– / Formatting

            æˆ‘ä»¬é¡¹ç›®ä¸­å„ç§ç¼–ç¨‹è¯­è¨€ä»£ç ï¼ˆåŒ…æ‹¬æ–‡æ¡£ï¼‰æ‰€é‡‡ç”¨çš„æ ¼å¼åŒ–å·¥å…·ä¸åŒï¼Œæäº¤ pr ä¹‹å‰å¿…é¡»ç¡®ä¿ä»£ç ã€æ–‡æ¡£æ­£ç¡®æ ¼å¼åŒ–ã€‚
            
            > We use different formatting tools for various programming languages (including documentation) in our project. You must ensure that the code and documentation are correctly formatted before submitting a pr.

            -   .{md,js,ts,php,sql} é‡‡ç”¨ prettier
            -   .{c,cpp,java} é‡‡ç”¨ clang-format
            -   .{py} é‡‡ç”¨ black
            -   .{go} é‡‡ç”¨ gofmt
            -   å…¶å®ƒå¾…å®Œå–„

            ### 2. Git æäº¤ä¿¡æ¯ / Git Commit Message

            æˆ‘ä»¬é¡¹ç›®éµå¾ª [AngularJS Git Commit Message Conventions](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#) è§„èŒƒï¼Œæˆ‘ä»¬å¸Œæœ›ä½ çš„æäº¤ä¿¡æ¯å°½å¯èƒ½ä¸Žé¡¹ç›®ä¿æŒä¸€è‡´ã€‚
            
            > Our project follows the [AngularJS Git Commit Message Conventions](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#). We hope that your submission information is as consistent as possible with the project.

            -   æ–°å¢žæˆ–ä¿®æ”¹é¢˜è§£ / Add or modify solutions: feat: add/update solution(s) to lc problem(s): No.xxxx
            -   ä¿®å¤é”™è¯¯ / Fix errors: fix: xxxx
            -   æ—¥å¸¸ç»´æŠ¤/ Routine maintenance: chore: xxx

            ### 3. å…¶å®ƒè¡¥å…… / Other notes

            æ–°å¢žé¢˜è§£åŠä»£ç æ—¶ï¼Œéœ€è¦åˆ›å»º Solution.xxx æºä»£ç æ–‡ä»¶ï¼ˆå¦‚æžœå·²å­˜åœ¨ï¼Œè¯·ç¡®è®¤ç®—æ³•æ˜¯å¦æ›´ä¼˜ï¼Œæ˜¯åˆ™è¦†ç›–å·²æœ‰ç®—æ³•ä»£ç ï¼‰ï¼ŒåŒæ—¶ï¼Œéœ€è¦åœ¨ README.md ä»¥åŠ README_EN.md ä¸­æ·»åŠ å¯¹åº”çš„ä»£ç ç‰‡æ®µï¼ˆè‹±æ–‡æ–‡ä»¶ä¸­ä¸è¦å‡ºçŽ°ä¸­æ–‡æ³¨é‡Šï¼‰
            
            > When adding solutions and code, you need to create a Solution.xxx source code file (if it already exists, please confirm whether the algorithm is better, if yes, overwrite the existing algorithm code), and at the same time, you need to add the corresponding code snippets in README.md and README_EN.md (do not have Chinese comments in the English file)

            å¦å¤–ï¼Œç¼–ç é£Žæ ¼ï¼ˆæ¯”å¦‚å˜é‡ã€å‡½æ•°çš„å‘½åï¼‰ï¼Œå°½é‡è·Ÿé¡¹ç›®å·²æœ‰ä»£ç ä¿æŒä¸€è‡´ã€‚ 
            
            > In addition, the coding style (such as the naming of variables and functions) should be as consistent as possible with the existing code in the project. 
            
            <!-- Sticky Pull Request Comment -->
          body-include: '<!-- Sticky Pull Request Comment -->'
